import os
from dotenv import load_dotenv

load_dotenv()

CHUNK_SIZE = int(os.getenv("CHUNK_SIZE"))
OVERLAP_SIZE = int(os.getenv("OVERLAP_SIZE"))
EMBEDDING_MODEL_1 = os.getenv("EMBEDDING_MODEL_1")
EMBEDDING_MODEL_2 = os.getenv("EMBEDDING_MODEL_2")
RETRIEVAL_TOP_K = int(os.getenv("RETRIEVAL_TOP_K"))
RERANK_TOP_K = int(os.getenv("RERANK_TOP_K"))
INDEX_PATH = os.getenv("INDEX_PATH")

LLM_CONTEXTUAL_PROVIDER = os.getenv("LLM_CONTEXTUAL_PROVIDER")
LLM_CONTEXTUAL_MODEL = os.getenv("LLM_CONTEXTUAL_MODEL")
LLM_CONTEXTUAL_CONTEXT_LENGTH = int(os.getenv("LLM_CONTEXTUAL_CONTEXT_LENGTH"))

LLM_GENERATIVE_PROVIDER = os.getenv("LLM_GENERATIVE_PROVIDER")
LLM_GENERATIVE_MODEL = os.getenv("LLM_GENERATIVE_MODEL")
LLM_GENERATIVE_CONTEXT_LENGTH = int(os.getenv("LLM_GENERATIVE_CONTEXT_LENGTH"))

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

DEBUG =  os.getenv("DEBUG", "false").lower() == "true"
