import os
from dotenv import load_dotenv

load_dotenv()

CHUNK_SIZE = int(os.getenv("CHUNK_SIZE"))
OVERLAP_SIZE = int(os.getenv("OVERLAP_SIZE"))
RETRIEVAL_TOP_K = int(os.getenv("RETRIEVAL_TOP_K"))
RERANK_TOP_K = int(os.getenv("RERANK_TOP_K"))
INDEX_PATH = os.getenv("INDEX_PATH")
LEXICAL_STORE_PATH = os.getenv("LEXICAL_STORE_PATH")
DOCUMENT_PATH = os.getenv("DOCUMENT_PATH")
CHUNKS_PATH = os.getenv("CHUNKS_PATH")
CONTEXT_CHUNKS_PATH = os.getenv("CONTEXT_CHUNKS_PATH")
DOCUMENT_LIMIT = int(os.getenv("DOCUMENT_LIMIT"))

EMBEDDING_PROVIDER = os.getenv("EMBEDDING_PROVIDER")
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL")
EMBEDDING_DIM = int(os.getenv("EMBEDDING_DIM"))

LLM_CONTEXTUAL_PROVIDER = os.getenv("LLM_CONTEXTUAL_PROVIDER")
LLM_CONTEXTUAL_MODEL = os.getenv("LLM_CONTEXTUAL_MODEL")
LLM_CONTEXTUAL_CONTEXT_LENGTH = int(os.getenv("LLM_CONTEXTUAL_CONTEXT_LENGTH"))

LLM_GENERATIVE_PROVIDER = os.getenv("LLM_GENERATIVE_PROVIDER")
LLM_GENERATIVE_MODEL = os.getenv("LLM_GENERATIVE_MODEL")
LLM_GENERATIVE_CONTEXT_LENGTH = int(os.getenv("LLM_GENERATIVE_CONTEXT_LENGTH"))

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

HUGGINGFACE_HUB_TOKEN = os.getenv("HUGGINGFACE_HUB_TOKEN")

DEBUG =  os.getenv("DEBUG", "false").lower() == "true"
